global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'airflow'
    metrics_path: /metrics
    basic_auth:
      username: airflow
      password: airflow
    static_configs:
      - targets:
        - 'airflow-scheduler:8793'
        - 'airflow-triggerer:8794'
        #- 'airflow-webserver:8080'